/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package anagha.plugins;

import anagha.UI;
import com.jayway.jsonpath.JsonPath;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author shanky
 */
public class similarsearch extends javax.swing.JFrame {

    
    String url;
    String response;
    URL obj;
    HttpURLConnection con;
    int responseCode;
    BufferedReader in;

    /**
     * Creates new form similarsearch
     */
    public similarsearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        site = new javax.swing.JTextField();
        execute = new javax.swing.JButton();
        back = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        value = new javax.swing.JTextArea();
        status = new javax.swing.JLabel();

        setTitle("Similar Search | Anaga");
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 300));

        site.setText("example.com");
        site.setToolTipText("example.com");
        site.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siteMouseClicked(evt);
            }
        });
        site.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                siteKeyPressed(evt);
            }
        });

        execute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/execute.png"))); // NOI18N
        execute.setToolTipText("Execute");
        execute.setBorder(null);
        execute.setBorderPainted(false);
        execute.setContentAreaFilled(false);
        execute.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        execute.setFocusPainted(false);
        execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        back.setToolTipText("Back");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setFocusPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        add.setToolTipText("Add to reports");
        add.setBorder(null);
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        value.setEditable(false);
        value.setColumns(20);
        value.setRows(5);
        jScrollPane2.setViewportView(value);

        status.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(execute, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(site, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(execute))
                    .addComponent(site, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void siteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siteMouseClicked

        if (site.getText().equals("example.com"))
        {
            site.setText("");
        }
    }//GEN-LAST:event_siteMouseClicked

    private void siteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_siteKeyPressed

        if (site.getText().equals("example.com"))
        {
            site.setText("");
        }
    }//GEN-LAST:event_siteKeyPressed

    private void executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeActionPerformed

        try {
            url = "http://www.similarsitesearch.com/api/similar/"+site.getText();
            obj = new URL(url);
            con = (HttpURLConnection) obj.openConnection();
            con.setRequestProperty("User-Agent", "Anagha");
            responseCode = con.getResponseCode();
            if(responseCode != 200)
            {
                status.setText("Cannot Process");
            }
            else
            {
                in = new BufferedReader(new InputStreamReader(con.getInputStream()));
                response=in.readLine();
                String r0 = JsonPath.read(response, "$.r0");
                String r1 = JsonPath.read(response, "$.r1");
                String r2 = JsonPath.read(response, "$.r2");
                String r3 = JsonPath.read(response, "$.r3");
                String r4 = JsonPath.read(response, "$.r4");
                String r5 = JsonPath.read(response, "$.r5");
                String r6 = JsonPath.read(response, "$.r6");
                String r7 = JsonPath.read(response, "$.r7");
                String r8 = JsonPath.read(response, "$.r8");
                String r9 = JsonPath.read(response, "$.r9");
                String r10 = JsonPath.read(response, "$.r10");
                String r11 = JsonPath.read(response, "$.r11");
                String r12 = JsonPath.read(response, "$.r12");
                String r13 = JsonPath.read(response, "$.r13");
                String r14 = JsonPath.read(response, "$.r14");
                String r15 = JsonPath.read(response, "$.r15");
                String r16 = JsonPath.read(response, "$.r16");
                String r17 = JsonPath.read(response, "$.r17");
                String r18 = JsonPath.read(response, "$.r18");
                String r19 = JsonPath.read(response, "$.r19");
                value.append("Total: "+JsonPath.read(response, "$.num"));
                value.append("\n"+"Status: "+JsonPath.read(response, "$.status"));
                if(r0!=null) {
                value.append("\n"+"URL's: \n");
                value.append(r0+"\n");
                value.append(r1+"\n");
                value.append(r2+"\n");
                value.append(r3+"\n");
                value.append(r4+"\n");
                value.append(r5+"\n");
                value.append(r6+"\n");
                value.append(r7+"\n");
                value.append(r8+"\n");
                value.append(r9+"\n");
                value.append(r10+"\n");
                value.append(r11+"\n");
                value.append(r12+"\n");
                value.append(r13+"\n");
                value.append(r14+"\n");
                value.append(r15+"\n");
                value.append(r16+"\n");
                value.append(r17+"\n");
                value.append(r18+"\n");
                value.append(r19+"\n");
                }
                in.close();
                status.setText("Finished");
            }
        } catch (IOException ex) {
            Logger.getLogger(geoip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_executeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        UI u= new UI();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(similarsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(similarsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(similarsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(similarsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new similarsearch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton execute;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField site;
    private javax.swing.JLabel status;
    private javax.swing.JTextArea value;
    // End of variables declaration//GEN-END:variables
}
